version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15
    container_name: pg01
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api01
    build:
      dockerfile: app/Dockerfile
    depends_on:
      elastic:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  frontend:
    container_name: frontend01
    build:
      dockerfile: app/frontend/Dockerfile
    depends_on:
      - api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
